### ISSUE TITLE
can not load the python interpreter

### ISSUE THREAD

**Issue by hwk0809** [GilbertPan97/RobCalib_AXYB#2]
Hello, after reading your paper, I tried to reproduce your excellent work, but when I opened it in Pychar and tried to load it in the Python environment, I couldn't load it

**Comment by GilbertPan97** [comment]
> Hello, after reading your paper, I tried to reproduce your excellent work, but when I opened it in Pychar and tried to load it in the Python environment, I couldn't load it

Thank you for showing interest in my work and trying to reproduce the results. I apologize for any inconvenience you faced while trying to load the Python environment in PyCharm.

It seems that there might be an issue with the compatibility of the Python environment you downloaded. Please note that the Python environment provided in the repository was built specifically for macOS and may not be directly usable on other systems.

To resolve this, I have now updated the README documentation with detailed instructions on how to set up the development environment properly. Please refer to the usage guidelines provided in the README and configure your development environment accordingly.

If you encounter any further difficulties or have any questions, please don't hesitate to reach out. I am here to assist you throughout the process.
